### ISSUE TITLE
backend deployment

### ISSUE THREAD

**Issue by rmartis** [sawden/turbostrapi#3]
Hello, could you help me, please?

I like your project, it seems like a good concept for the future, but I have a problem with production deployment. I would like to deploy frontend on Vercel and backend on digitalocean app.  I am mainly interested in digitalocean deployment.  Turbo Repo is a fairly new project and not easy to find some instructions.

Where do you deploy the backend for [turbostrapi.vercel.app](https://turbostrapi.vercel.app/) ?

**Comment by codeplott** [comment]
Hi there,

Thank you for your interest in TurboStrapi 🙂! 

Regarding deployment, for [turbostrapi.vercel.app](https://turbostrapi.vercel.app), the Strapi backend is deployed on an Ubuntu server using [Docker](https://www.docker.com/) with [Traefik](https://doc.traefik.io/traefik/), a reverse proxy I highly recommend. While there are countless ways to deploy Strapi, I prefer this approach for all my projects due to Traefik's ease of setup, especially with self-signed certificates, making any deployment quick and easy.

I've shared my Traefik and TurboStrapi with Traefik configuration in two separate repositories. These should provide a good starting point, but they do require some familiarity with Traefik and Docker, as not every detail is documented. 

Here are the links:
[Traefik Base Configuration](https://github.com/sawden/traefik-base)
[TurboStrapi Traefik Configuration](https://github.com/sawden/traefik-turbostrapi)

If you're planning to deploy only the Strapi backend, you can adjust the `docker-compose.yml` in the second repository by commenting out the 'frontend' service section. Keep in mind that the frontend requires the backend to be deployed first, as it cannot be built independently.

Also, there are great [tutorials on YouTube about Traefik](https://www.youtube.com/results?search_query=traefik), for more complex issues, the official [docs](https://doc.traefik.io/traefik/) and the [community forum](https://community.traefik.io/) are very helpful.

I hope this helps, and best of luck with your deployment 🚀!

**Comment by rmartis** [comment]
Hi sawden,

Thank you for your answer. You've helped me a lot.
I used both your repo, [traefik-base](https://github.com/sawden/traefik-base) + [traefik-turbostrapi](https://github.com/sawden/traefik-turbostrapi) and backend is alive ;) with reverse proxy 🚀 + portainer.

Your use of typescript types in frontend development made my life easier, but could you please add some image section, because I have a problem with image type... there is **any** type. Maybe I'm doing something wrong :(

my image-section.tsx:

```
import * as React from 'react'
import { Attribute } from '@/types'
import Image from 'next/image'

export interface ImageSectionProps extends React.HTMLAttributes<HTMLDivElement> {
  section: Attribute.GetDynamicZoneValue<Attribute.DynamicZone<['sections.image-section']>>[number]
}

const ImageSection = React.forwardRef<HTMLDivElement, ImageSectionProps>(({ section }, ref) => {
  if (section.image) {
    console.log(section.image)
    return <Image src={section.image} alt="image" {...ref} />
  }
})

ImageSection.displayName = 'Image Section'

export { ImageSection }
```

U can see :

```
(property) ImageSectionProps.section: {
    id: ID;
} & {
    image: any;
} & {
    caption?: string | undefined;
} & {
    __component: "sections.image-section";
}
```

thank you, Roman
