### ISSUE TITLE
New Shadcn Components 

### ISSUE THREAD

**Issue by capsloq** [sawden/turbostrapi#4]
Hello,

first of all WOW!
This repo is crazy. Typesafety between FE und BE this is straight a more lean TRPC.
I really love this. I hope this gets a lot more attention.

This is my first touch with turborepo, so my question might be noobish:
I am assuming you are using some Shadcn components (dropdown, button)
But the components seem to be in `packages/ui` which itself is included in the `frontend/package.json`.
So why do you chose a custom `packages` folder outside of the frontend? Is this due to turborepo?

Also, I was expecting a [components.json](https://ui.shadcn.com/docs/components-json) but did not find one.
How would one add new Shadcn components?

Thank you and well well well done

**Comment by codeplott** [comment]
Hi,

It's great to hear you appreciate the project! 🙂

I chose to place the UI components in a separate workspace for potential reuse across different apps within the monorepo, like, for example, a Storybook that showcases all UI elements.

However, Shadcn is not set up in the project yet, even though some components are used. It's something on my list, but I haven't gotten around to it yet.

If you're not planning to reuse the UI components across different apps, simplifying the setup by initializing Shadcn directly in `apps/frontend` and removing the `packages/ui` might be the best approach.

Useful hint: you will notice that the media types (image, video, audio) are currently typed as `any`. This is because Strapi has defined them as `any` in their code, as you can see [here](https://github.com/strapi/strapi/issues/19353). 
This will hopefully change with version 5, whose public beta release is planned for today 🎉

If you plan on hosting Strapi yourself, I've also published my configurations for that: https://github.com/sawden/turbostrapi/issues/3

Wishing you all the best with your project!

**Comment by capsloq** [comment]
Thank you for the reply.
It's great to hear you are already thinking of Strapi v5.
I had the exact same thought yesterday, when I first saw your project: _This is going to be even better with Strapi v5 since they do a full rewrite in Typescript._

Also thank you for the explanation of the reusable UI components i got the idea.

Regarding deployment i was thinking of giving Strapi Cloud a try, just to test it out.
Don't really know if that is even possible with the Turborepo setup, however i am willing to get on the journey learning some Monorepo / Turborepo basics. This project just showed me the power of it, now i wanna know more :-)
Nevertheless i did read the deployment guide with Traefik.

Edit to let you know:
Strapi v5 beta got pushed. Screenshot from their Discord:
![image](https://github.com/sawden/turbostrapi/assets/73945900/b92371a9-4707-446d-92f2-e8b2113e746e)

**Comment by codeplott** [comment]
Thanks for the heads up about Strapi v5's delay! 
Honestly, I almost expected it. We developers know the struggle all too well! 😄
